### PR TITLE
Bugfix/issue 3

### PR DESCRIPTION
**Pull request by Lezzma**
User interface issue for different Android devices, resolved.

### CODE REVIEW

**Comment by yangray1** [comment]
Hi @Lezzma @Jose-WDG , This is great! I was also wondering if you could fix the camera view as well 
**(You can get to this page by clicking the "Scan barcode" in activity_main)**




**Left**: Nexus 5 API 28 device (camera view too large)   **Right**: Pixel 2 API 28 device (Correct sizing)
Screen Shot 2019-10-07 at 6 55 40 PM

Thanks!

**Review by yangray1 — APPROVED** [review]

**Comment by Lezzma** [comment]
ok, my fix the camera.
________________________________
De: Raymond <notifications@github.com>
Enviado: segunda-feira, 7 de outubro de 2019 19:57
Para: yangray1/Price-Scam-Detector <Price-Scam-Detector@noreply.github.com>
Cc: Lezzma <neto.silva101@outlook.com>; Mention <mention@noreply.github.com>
Assunto: Re: [yangray1/Price-Scam-Detector] Bugfix/issue 3 (#4)


Hi @Lezzma<https://github.com/Lezzma> , This is great! I was also wondering if you could fix the camera view as well:

Left: Nexus 5 API 28 device. Right: Pixel 2 API 28 device:
[Screen Shot 2019-10-07 at 6 55 40 PM]<https://user-images.githubusercontent.com/39708793/66354868-2fbd0a00-e934-11e9-959b-a8909581d444.png>

Thanks!

**Comment by Lezzma** [comment]
josé Ramalho is lezzma, rs´s.

**Comment by yangray1** [comment]
@Lezzma  is it possible if you can leave this open, i'm thinking of merging all my PRs next week

**Pull request closed without merging**
